### ISSUE TITLE
why is not working

### ISSUE THREAD

**Issue by abdo-spices** [jgerigmeyer/true-vitest#1]
![Screenshot_27](https://user-images.githubusercontent.com/93441520/199523156-efc0d507-f0df-4e05-9bfa-9aff3e1636d4.png)
![Screenshot_26](https://user-images.githubusercontent.com/93441520/199524258-db09a09f-1064-4b42-8d2f-f2bd08f5372c.png)

**Comment by abdo-spices** [comment]
@jgerigmeyer

**Comment by jgerigmeyer** [comment]
@blackPeppper I think this issue was probably intended for https://github.com/oddbird/true, not this repo?

But in any case, it looks like you're using the API from v7, which is still in beta. I'm guessing you have v6.1.0 installed? If so, follow the readme from that release: https://github.com/oddbird/true/tree/v6.1.0 or https://www.oddbird.net/true/docs/
